name: cinema_ticket_bookings
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.5
  cupertino_icons: ^0.1.2
  carousel_slider: ^2.1.0
  expansion_tile_card: ^1.0.3
  intl: ^0.16.1
  bidirectional_scroll_view: ^0.1.1
  qr_flutter: ^3.1.0
  scroll_snap_list: ^0.4.0
  http: ^0.12.1
  shared_preferences: ^0.5.7+2
  flutter_phoenix: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  image_path: 'dev_assets/movies.png'
  adaptive_icon_background: '#121212'
  adaptive_icon_foreground: 'dev_assets/movies-adaptive.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BalsamiqSans
      fonts:
        - asset: assets/fonts/BalsamiqSans-Regular.ttf
        - asset: assets/fonts/BalsamiqSans-Bold.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 400
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
